"use client";

import { useEffect, useState } from "react";
import { Bot, Check, Clock3, Database, Eye, MessageSquareText, Palette, Save, Send, Settings2, ShieldCheck, Sparkles } from "lucide-react";
import { api } from "../lib/api";

type SettingsResult = { values: Record<string, string>; canManage: boolean; smsApiKeyConfigured: boolean; aiRuntime: string };
type Tab = "عمومی" | "هوش مصنوعی" | "پیامک" | "ظاهر و تم" | "امنیت و پشتیبان";
const themes = [{ id: "ocean", name: "اقیانوس سپه", colors: ["#064d68", "#11b7d0", "#dff8fb"] }, { id: "midnight", name: "شب مدیریتی", colors: ["#071e35", "#15557a", "#79d9eb"] }, { id: "pearl", name: "مروارید روشن", colors: ["#eefbfc", "#7acbd9", "#087b9c"] }, { id: "sepah", name: "رسمی سپه", colors: ["#06354d", "#087fa3", "#ef8b2c"] }];

export default function SettingsWorkspace({ collapsed }: { collapsed: boolean }) {
  const [data, setData] = useState<SettingsResult | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});
  const [tab, setTab] = useState<Tab>("عمومی");
  const [notice, setNotice] = useState("");
  useEffect(() => { api<SettingsResult>("/settings").then((result) => { setData(result); setValues(result.values); }).catch(() => undefined); }, []);
  function set(key: string, value: string) { setValues((current) => ({ ...current, [key]: value })); if (key === "Theme.Name") document.documentElement.dataset.theme = value; }
  async function save() { try { await api<void>("/settings", { method:"PUT", body:JSON.stringify({ values }) }); localStorage.setItem("sepah-theme", values["Theme.Name"] ?? "ocean"); window.dispatchEvent(new CustomEvent("sepah-settings-changed", { detail: values })); setNotice("تنظیمات با موفقیت ذخیره شد."); } catch (error) { setNotice(error instanceof Error ? error.message : "ذخیره انجام نشد."); } window.setTimeout(() => setNotice(""), 2600); }
  async function testSms() { try { const result = await api<{message:string}>("/settings/sms/test", { method:"POST" }); setNotice(result.message); } catch (error) { setNotice(error instanceof Error ? error.message : "آزمایش پیامک انجام نشد."); } window.setTimeout(() => setNotice(""), 3500); }
  if (!data) return <section className={`projects-workspace settings-workspace ${collapsed ? "sidebar-collapsed" : ""}`}><div className="tenant-loading">در حال دریافت تنظیمات سازمان…</div></section>;
  const tabs: Array<{label:Tab;icon:typeof Settings2}> = [{label:"عمومی",icon:Settings2},{label:"هوش مصنوعی",icon:Bot},{label:"پیامک",icon:MessageSquareText},{label:"ظاهر و تم",icon:Palette},{label:"امنیت و پشتیبان",icon:ShieldCheck}];
  return <section className={`projects-workspace settings-workspace ${collapsed ? "sidebar-collapsed" : ""}`}>
    <header className="settings-heading"><div><span><Settings2 size={25} /></span><div><small>مرکز پیکربندی سازمان</small><h1>تنظیمات سامانه</h1><p>هوش مصنوعی، پیامک، ظاهر و سیاست‌های عمومی Tenant فعال</p></div></div><div><ShieldCheck size={17} /><span>تنظیمات مستقل سازمانی</span></div></header>
    <nav className="settings-tabs">{tabs.map((item) => { const Icon=item.icon; return <button className={tab===item.label?"active":""} onClick={() => setTab(item.label)} key={item.label}><Icon size={18}/>{item.label}</button>; })}</nav>
    <section className="settings-card">
      {tab === "عمومی" && <><header><div><strong>تنظیمات عمومی</strong><p>مشخصات پایه و شیوه نمایش تاریخ در سازمان</p></div><Settings2 size={22}/></header><div className="settings-form-grid"><label><span>نام سازمان</span><input value={values["General.OrganizationName"] ?? ""} onChange={(e)=>set("General.OrganizationName",e.target.value)}/></label><label><span>منطقه زمانی</span><select value={values["General.TimeZone"] ?? "Asia/Tehran"} onChange={(e)=>set("General.TimeZone",e.target.value)}><option>Asia/Tehran</option><option>UTC</option></select></label><Toggle title="تقویم شمسی" description="نمایش و ورود همه تاریخ‌ها به تقویم جلالی" checked={values["General.PersianCalendar"]!=="false"} onChange={(v)=>set("General.PersianCalendar",String(v))}/><article className="setting-info"><Clock3 size={22}/><div><strong>زمان رسمی سامانه</strong><p>همه رویدادها در دیتابیس با UTC و در رابط با زمان تهران نمایش داده می‌شوند.</p></div></article></div></>}
      {tab === "هوش مصنوعی" && <><header><div><strong>تنظیمات دستیار هوشمند</strong><p>موتور تحلیل و محدوده داده مجاز برای پاسخ‌گویی</p></div><Bot size={23}/></header><div className="ai-settings-hero"><span><Sparkles size={25}/></span><div><strong>{data.aiRuntime}</strong><p>بدون ارسال داده به سرویس پولی؛ پاسخ‌ها داخل زیرساخت شما ساخته می‌شوند.</p></div><em>رایگان</em></div><div className="settings-form-grid"><Toggle title="فعال‌بودن دستیار AI" description="نمایش و امکان گفت‌وگو با Sepah Insight" checked={values["Ai.Enabled"]!=="false"} onChange={(v)=>set("Ai.Enabled",String(v))}/><Toggle title="استفاده از داده پروژه‌ها" description="تحلیل فقط داده‌های Tenant و پروژه‌های مجاز کاربر" checked={values["Ai.IncludeProjectData"]!=="false"} onChange={(v)=>set("Ai.IncludeProjectData",String(v))}/><label><span>موتور هوش مصنوعی</span><select value={values["Ai.Provider"] ?? "SepahInsight"} onChange={(e)=>set("Ai.Provider",e.target.value)}><option value="SepahInsight">Sepah Insight داخلی — فوری و رایگان</option><option value="Ollama">Ollama محلی — مدل زبانی رایگان</option></select></label><label><span>مدل Ollama</span><select value={values["Ai.Model"] ?? "qwen2.5:3b"} onChange={(e)=>set("Ai.Model",e.target.value)}><option>qwen2.5:3b</option><option>qwen2.5:7b</option><option>llama3.2:3b</option><option>gemma2:2b</option></select></label><label className="wide"><span>آدرس سرویس Ollama</span><input dir="ltr" value={values["Ai.OllamaUrl"] ?? "http://localhost:11434"} onChange={(e)=>set("Ai.OllamaUrl",e.target.value)}/></label><article className="setting-info wide"><Database size={22}/><div><strong>حریم داده اجباری است</strong><p>حتی AI نیز فقط داده‌های سازمان فعال و پروژه‌های مجاز را می‌خواند؛ Tenant دیگر قابل دسترس نیست.</p></div></article></div></>}
      {tab === "پیامک" && <><header><div><strong>درگاه پیامک و هشدار</strong><p>ارسال اعلان‌های مهم به مدیران و مسئولان اقدام</p></div><MessageSquareText size={23}/></header><div className="sms-status"><span className={data.smsApiKeyConfigured?"ready":"pending"}><i/>{data.smsApiKeyConfigured?"کلید درگاه تنظیم شده":"نیازمند کلید درگاه"}</span><p>کلید محرمانه در کد یا دیتابیس ذخیره نمی‌شود و باید با متغیر امن SMS_API_KEY تنظیم شود.</p></div><div className="settings-form-grid"><Toggle title="فعال‌سازی پیامک" description="ارسال خودکار طبق رویدادهای انتخاب‌شده" checked={values["Sms.Enabled"]==="true"} onChange={(v)=>set("Sms.Enabled",String(v))}/><label><span>ارائه‌دهنده</span><select value={values["Sms.Provider"] ?? "کاوه‌نگار"} onChange={(e)=>set("Sms.Provider",e.target.value)}><option>کاوه‌نگار</option><option>ملی پیامک</option><option>فراز اس‌ام‌اس</option><option>درگاه اختصاصی بانک</option></select></label><label><span>شماره فرستنده</span><input dir="ltr" value={values["Sms.SenderNumber"] ?? ""} placeholder="3000..." onChange={(e)=>set("Sms.SenderNumber",e.target.value)}/></label><label><span>سقف ارسال روزانه</span><input type="number" value={values["Sms.DailyLimit"] ?? "500"} onChange={(e)=>set("Sms.DailyLimit",e.target.value)}/></label><div className="sms-events wide"><strong>رویدادهای ارسال پیامک</strong>{[{id:"approval",label:"درخواست تأیید"},{id:"dueDate",label:"نزدیک‌شدن موعد"},{id:"criticalRisk",label:"ریسک بحرانی"},{id:"assignment",label:"ارجاع وظیفه"}].map((event)=>{const active=(values["Sms.Events"]??"").split(",").includes(event.id);return <label key={event.id}><input type="checkbox" checked={active} onChange={()=>{const setIds=new Set((values["Sms.Events"]??"").split(",").filter(Boolean));if(active)setIds.delete(event.id);else setIds.add(event.id);set("Sms.Events",Array.from(setIds).join(","));}}/><i/>{event.label}</label>})}</div><button className="settings-test wide" onClick={()=>void testSms()}><Send size={16}/> آزمایش تنظیمات پیامک</button></div></>}
      {tab === "ظاهر و تم" && <><header><div><strong>ظاهر و تم سامانه</strong><p>نمایش مدیرپسند و هماهنگ با محیط کاری</p></div><Palette size={23}/></header><div className="theme-picker">{themes.map((theme)=><button className={(values["Theme.Name"]??"ocean")===theme.id?"active":""} onClick={()=>set("Theme.Name",theme.id)} key={theme.id}><span>{theme.colors.map((color)=><i style={{background:color}} key={color}/>)}</span><strong>{theme.name}</strong>{(values["Theme.Name"]??"ocean")===theme.id&&<Check size={16}/>}</button>)}</div><div className="settings-form-grid"><label><span>تراکم رابط</span><select value={values["Theme.Density"]??"comfortable"} onChange={(e)=>set("Theme.Density",e.target.value)}><option value="comfortable">راحت و مدیرپسند</option><option value="compact">فشرده و اطلاعاتی</option></select></label><label><span>شدت شیشه‌ای بودن: {values["Theme.GlassIntensity"]??"82"}٪</span><input type="range" min="45" max="100" value={values["Theme.GlassIntensity"]??"82"} onChange={(e)=>set("Theme.GlassIntensity",e.target.value)}/></label><Toggle title="حرکت‌های ظریف رابط" description="انیمیشن بازشدن پنل‌ها و Hover کارت‌ها" checked={values["Theme.Motion"]!=="false"} onChange={(v)=>set("Theme.Motion",String(v))}/><article className="theme-preview"><Eye size={20}/><div><strong>پیش‌نمایش زنده</strong><p>انتخاب تم بلافاصله در همین صفحه اعمال می‌شود.</p></div></article></div></>}
      {tab === "امنیت و پشتیبان" && <><header><div><strong>امنیت و پایداری</strong><p>وضعیت کنترل‌های اصلی سامانه</p></div><ShieldCheck size={23}/></header><div className="security-setting-grid"><article><ShieldCheck/><strong>احراز هویت Cookie امن</strong><span>فعال</span></article><article><Database/><strong>جداسازی Tenant در SQL Server</strong><span>فعال</span></article><article><Bot/><strong>محدودسازی داده AI</strong><span>فعال</span></article><article><Save/><strong>پشتیبان‌گیری زمان‌بندی‌شده</strong><span className="warning">نیازمند تنظیم Job</span></article></div></>}
      <footer><span>{data.canManage?"تغییرات برای سازمان فعال ذخیره می‌شود.":"دسترسی شما فقط مشاهده است."}</span><button disabled={!data.canManage} onClick={()=>void save()}><Save size={17}/> ذخیره تنظیمات</button></footer>
    </section>{notice&&<div className="settings-notice"><Check size={16}/>{notice}</div>}
  </section>;
}

function Toggle({title,description,checked,onChange}:{title:string;description:string;checked:boolean;onChange:(value:boolean)=>void}) { return <label className="setting-toggle"><div><strong>{title}</strong><small>{description}</small></div><input aria-label={title} type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><i/></label>; }
